<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 10 FROC sample size estimation | The RJafroc Quick Start Book</title>
  <meta name="description" content="This book is for those already somewhat familiar running Windows JAFROC to analyze data. The Windows program has been replaced by RJafroc. This book dives into how to use RJafroc to analyze ROC/FROC data." />
  <meta name="generator" content="bookdown 0.34 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 10 FROC sample size estimation | The RJafroc Quick Start Book" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This book is for those already somewhat familiar running Windows JAFROC to analyze data. The Windows program has been replaced by RJafroc. This book dives into how to use RJafroc to analyze ROC/FROC data." />
  <meta name="github-repo" content="dpc10ster/RJafrocQuickStart" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 10 FROC sample size estimation | The RJafroc Quick Start Book" />
  
  <meta name="twitter:description" content="This book is for those already somewhat familiar running Windows JAFROC to analyze data. The Windows program has been replaced by RJafroc. This book dives into how to use RJafroc to analyze ROC/FROC data." />
  

<meta name="author" content="Dev P. Chakraborty, PhD" />


<meta name="date" content="2023-05-09" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="analyzing-froc-data.html"/>
<link rel="next" href="dataset-object-details.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">RJafroc documentation</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preface</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#quick-start-index-rationale-and-organization"><i class="fa fa-check"></i><b>1.1</b> Rationale and Organization</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#quick-start-index-getting-help"><i class="fa fa-check"></i><b>1.2</b> Getting help on the software</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#quick-start-index-acknowledgements"><i class="fa fa-check"></i><b>1.3</b> Acknowledgements</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="index.html"><a href="index.html#persons-who-have-stimulated-my-thinking"><i class="fa fa-check"></i><b>1.3.1</b> Persons who have stimulated my thinking:</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#quick-start-index-contributors"><i class="fa fa-check"></i><b>1.4</b> Contributors to the software</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#quick-start-index-dataset-contributors"><i class="fa fa-check"></i><b>1.5</b> Dataset contributors</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#quick-start-index-how-to-access-files"><i class="fa fa-check"></i><b>1.6</b> Accessing files and code</a></li>
</ul></li>
<li class="part"><span><b>Quick Start</b></span></li>
<li class="chapter" data-level="2" data-path="quick-start-roc.html"><a href="quick-start-roc.html"><i class="fa fa-check"></i><b>2</b> ROC data format</a>
<ul>
<li class="chapter" data-level="2.1" data-path="quick-start-roc.html"><a href="quick-start-roc.html#quick-start-roc-how-much-finished"><i class="fa fa-check"></i><b>2.1</b> How much finished 50%</a></li>
<li class="chapter" data-level="2.2" data-path="quick-start-roc.html"><a href="quick-start-roc.html#quick-start-roc-intro"><i class="fa fa-check"></i><b>2.2</b> Introduction</a></li>
<li class="chapter" data-level="2.3" data-path="quick-start-roc.html"><a href="quick-start-roc.html#quick-start-roc-note"><i class="fa fa-check"></i><b>2.3</b> Note to existing users</a></li>
<li class="chapter" data-level="2.4" data-path="quick-start-roc.html"><a href="quick-start-roc.html#quick-start-roc-excel"><i class="fa fa-check"></i><b>2.4</b> Three worksheets in the Excel data file</a>
<ul>
<li class="chapter" data-level="2.4.1" data-path="quick-start-roc.html"><a href="quick-start-roc.html#quick-start-roc-truth"><i class="fa fa-check"></i><b>2.4.1</b> The <code>Truth</code> worksheet</a></li>
<li class="chapter" data-level="2.4.2" data-path="quick-start-roc.html"><a href="quick-start-roc.html#quick-start-roc-truth-comments"><i class="fa fa-check"></i><b>2.4.2</b> Comments on the <code>Truth</code> worksheet</a></li>
<li class="chapter" data-level="2.4.3" data-path="quick-start-roc.html"><a href="quick-start-roc.html#quick-start-roc-fp"><i class="fa fa-check"></i><b>2.4.3</b> The FP/NL worksheet</a></li>
<li class="chapter" data-level="2.4.4" data-path="quick-start-roc.html"><a href="quick-start-roc.html#quick-start-roc-tp"><i class="fa fa-check"></i><b>2.4.4</b> The TP/LL worksheet</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="quick-start-roc.html"><a href="quick-start-roc.html#quick-start-roc-read"><i class="fa fa-check"></i><b>2.5</b> Reading the Excel file</a></li>
<li class="chapter" data-level="2.6" data-path="quick-start-roc.html"><a href="quick-start-roc.html#quick-start-roc-structure-dataset"><i class="fa fa-check"></i><b>2.6</b> Structure of dataset object</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="quick-start-froc-data-format.html"><a href="quick-start-froc-data-format.html"><i class="fa fa-check"></i><b>3</b> FROC data format</a>
<ul>
<li class="chapter" data-level="3.1" data-path="quick-start-froc-data-format.html"><a href="quick-start-froc-data-format.html#quick-start-froc-how-much-finished"><i class="fa fa-check"></i><b>3.1</b> How much finished 90%</a></li>
<li class="chapter" data-level="3.2" data-path="quick-start-froc-data-format.html"><a href="quick-start-froc-data-format.html#quick-start-froc-data-intro"><i class="fa fa-check"></i><b>3.2</b> Introduction</a></li>
<li class="chapter" data-level="3.3" data-path="quick-start-froc-data-format.html"><a href="quick-start-froc-data-format.html#quick-start-froc-data-truth"><i class="fa fa-check"></i><b>3.3</b> The <code>Truth</code> worksheet</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="quick-start-froc-data-format.html"><a href="quick-start-froc-data-format.html#quick-start-froc-truth-comments"><i class="fa fa-check"></i><b>3.3.1</b> Comments on the <code>Truth</code> worksheet</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="quick-start-froc-data-format.html"><a href="quick-start-froc-data-format.html#quick-start-froc-data-fp"><i class="fa fa-check"></i><b>3.4</b> The FP ratings</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="quick-start-froc-data-format.html"><a href="quick-start-froc-data-format.html#quick-start-roc-fp-comments"><i class="fa fa-check"></i><b>3.4.1</b> Comments on the <code>FP</code> worksheet</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="quick-start-froc-data-format.html"><a href="quick-start-froc-data-format.html#quick-start-froc-data-tp"><i class="fa fa-check"></i><b>3.5</b> The TP ratings</a></li>
<li class="chapter" data-level="3.6" data-path="quick-start-froc-data-format.html"><a href="quick-start-froc-data-format.html#quick-start-froc-data-structure"><i class="fa fa-check"></i><b>3.6</b> Reading the FROC dataset</a></li>
<li class="chapter" data-level="3.7" data-path="quick-start-froc-data-format.html"><a href="quick-start-froc-data-format.html#quick-start-froc-data-distribution-diseased-cases"><i class="fa fa-check"></i><b>3.7</b> The distribution of lesions in diseased cases</a>
<ul>
<li class="chapter" data-level="3.7.1" data-path="quick-start-froc-data-format.html"><a href="quick-start-froc-data-format.html#quick-start-froc-data-lesion-distribution"><i class="fa fa-check"></i><b>3.7.1</b> Definition of <code>lesID</code> array</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="quick-start-froc-data-format.html"><a href="quick-start-froc-data-format.html#quick-start-froc-data-lesion-weights"><i class="fa fa-check"></i><b>3.8</b> Lesion weights</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="quick-start-lroc.html"><a href="quick-start-lroc.html"><i class="fa fa-check"></i><b>4</b> LROC data format</a>
<ul>
<li class="chapter" data-level="4.1" data-path="quick-start-lroc.html"><a href="quick-start-lroc.html#quick-start-lroc-data-how-much-finished"><i class="fa fa-check"></i><b>4.1</b> How much finished 75%</a></li>
<li class="chapter" data-level="4.2" data-path="quick-start-lroc.html"><a href="quick-start-lroc.html#quick-start-lroc-data-intro"><i class="fa fa-check"></i><b>4.2</b> Introduction</a></li>
<li class="chapter" data-level="4.3" data-path="quick-start-lroc.html"><a href="quick-start-lroc.html#quick-start-lroc-data-forced-vs-not-forced"><i class="fa fa-check"></i><b>4.3</b> Forced vs. not-forced marks</a></li>
<li class="chapter" data-level="4.4" data-path="quick-start-lroc.html"><a href="quick-start-lroc.html#quick-start-lroc-truth"><i class="fa fa-check"></i><b>4.4</b> <code>Truth</code> worksheet</a></li>
<li class="chapter" data-level="4.5" data-path="quick-start-lroc.html"><a href="quick-start-lroc.html#quick-start-lroc-tp1"><i class="fa fa-check"></i><b>4.5</b> <code>TP</code> worksheet, forced localization true</a></li>
<li class="chapter" data-level="4.6" data-path="quick-start-lroc.html"><a href="quick-start-lroc.html#quick-start-lroc-fp1"><i class="fa fa-check"></i><b>4.6</b> <code>FP</code> worksheet, forced localization true</a></li>
<li class="chapter" data-level="4.7" data-path="quick-start-lroc.html"><a href="quick-start-lroc.html#quick-start-lroc-data-1"><i class="fa fa-check"></i><b>4.7</b> Reading forced localization true LROC dataset</a></li>
<li class="chapter" data-level="4.8" data-path="quick-start-lroc.html"><a href="quick-start-lroc.html#quick-start-lroc-tp2"><i class="fa fa-check"></i><b>4.8</b> <code>TP</code> worksheet, forced localization false</a></li>
<li class="chapter" data-level="4.9" data-path="quick-start-lroc.html"><a href="quick-start-lroc.html#quick-start-lroc-fp2"><i class="fa fa-check"></i><b>4.9</b> <code>FP</code> worksheet, forced localization false</a></li>
<li class="chapter" data-level="4.10" data-path="quick-start-lroc.html"><a href="quick-start-lroc.html#quick-start-lroc-data-2"><i class="fa fa-check"></i><b>4.10</b> Reading forced localization false LROC dataset</a></li>
<li class="chapter" data-level="4.11" data-path="quick-start-lroc.html"><a href="quick-start-lroc.html#quick-start-lroc-data-summary"><i class="fa fa-check"></i><b>4.11</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="quick-start-dbm-text.html"><a href="quick-start-dbm-text.html"><i class="fa fa-check"></i><b>5</b> DBM analysis text output</a>
<ul>
<li class="chapter" data-level="5.1" data-path="quick-start-dbm-text.html"><a href="quick-start-dbm-text.html#quick-start-dbm-text-how-much-finished"><i class="fa fa-check"></i><b>5.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="5.2" data-path="quick-start-dbm-text.html"><a href="quick-start-dbm-text.html#quick-start-dbm-text-intro"><i class="fa fa-check"></i><b>5.2</b> Introduction</a></li>
<li class="chapter" data-level="5.3" data-path="quick-start-dbm-text.html"><a href="quick-start-dbm-text.html#quick-start-dbm-text-analyze-dataset"><i class="fa fa-check"></i><b>5.3</b> Analyzing the ROC dataset</a></li>
<li class="chapter" data-level="5.4" data-path="quick-start-dbm-text.html"><a href="quick-start-dbm-text.html#quick-start-dbm-text-explanation"><i class="fa fa-check"></i><b>5.4</b> Explanation of the output</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="quick-start-or-text.html"><a href="quick-start-or-text.html"><i class="fa fa-check"></i><b>6</b> OR analysis text output</a>
<ul>
<li class="chapter" data-level="6.1" data-path="quick-start-or-text.html"><a href="quick-start-or-text.html#quick-start-or-text-how-much-finished"><i class="fa fa-check"></i><b>6.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="6.2" data-path="quick-start-or-text.html"><a href="quick-start-or-text.html#quick-start-or-text-intro"><i class="fa fa-check"></i><b>6.2</b> Introduction</a></li>
<li class="chapter" data-level="6.3" data-path="quick-start-or-text.html"><a href="quick-start-or-text.html#quick-start-or-text-analyze-dataset"><i class="fa fa-check"></i><b>6.3</b> Analyzing the ROC dataset</a></li>
<li class="chapter" data-level="6.4" data-path="quick-start-or-text.html"><a href="quick-start-or-text.html#quick-start-or-text-explanation"><i class="fa fa-check"></i><b>6.4</b> Explanation of the output</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="quick-start-or-excel.html"><a href="quick-start-or-excel.html"><i class="fa fa-check"></i><b>7</b> OR analysis Excel output</a>
<ul>
<li class="chapter" data-level="7.1" data-path="quick-start-or-excel.html"><a href="quick-start-or-excel.html#quick-start-or-excel-how-much-finished"><i class="fa fa-check"></i><b>7.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="7.2" data-path="quick-start-or-excel.html"><a href="quick-start-or-excel.html#quick-start-or-excel-intro"><i class="fa fa-check"></i><b>7.2</b> Introduction</a></li>
<li class="chapter" data-level="7.3" data-path="quick-start-or-excel.html"><a href="quick-start-or-excel.html#quick-start-or-excel-output"><i class="fa fa-check"></i><b>7.3</b> Generating the Excel output file</a></li>
</ul></li>
<li class="part"><span><b>ROC sample size</b></span></li>
<li class="chapter" data-level="8" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html"><i class="fa fa-check"></i><b>8</b> ROC-DBM sample size</a>
<ul>
<li class="chapter" data-level="8.1" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-how-much-finished"><i class="fa fa-check"></i><b>8.1</b> TBA How much finished 10%</a></li>
<li class="chapter" data-level="8.2" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-introduction"><i class="fa fa-check"></i><b>8.2</b> Introduction</a></li>
<li class="chapter" data-level="8.3" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#StatPower1"><i class="fa fa-check"></i><b>8.3</b> Statistical Power</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#observed-vs.-anticipated-effect-size"><i class="fa fa-check"></i><b>8.3.1</b> Observed vs. anticipated effect-size</a></li>
<li class="chapter" data-level="8.3.2" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-dependence-of-stats-power"><i class="fa fa-check"></i><b>8.3.2</b> Dependence of statistical power on estimates of model parameters</a></li>
<li class="chapter" data-level="8.3.3" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-RRRC-sample-size-estimation"><i class="fa fa-check"></i><b>8.3.3</b> Formulae for random-reader random-case (RRRC) sample size estimation</a></li>
<li class="chapter" data-level="8.3.4" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-sig-testing"><i class="fa fa-check"></i><b>8.3.4</b> Significance testing</a></li>
<li class="chapter" data-level="8.3.5" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-pvalue-ci"><i class="fa fa-check"></i><b>8.3.5</b> p-value and confidence interval</a></li>
<li class="chapter" data-level="8.3.6" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-CompareDBM2OR"><i class="fa fa-check"></i><b>8.3.6</b> Comparing DBM to Obuchowski and Rockette for single-reader multiple-treatments</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-FRRC-sample-size-estimation"><i class="fa fa-check"></i><b>8.4</b> Formulae for fixed-reader random-case (FRRC) sample size estimation</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-RRFC-sample-size-estimation"><i class="fa fa-check"></i><b>8.4.1</b> Formulae for random-reader fixed-case (RRFC) sample size estimation</a></li>
<li class="chapter" data-level="8.4.2" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-FRRCAnalysis"><i class="fa fa-check"></i><b>8.4.2</b> Fixed-reader random-case (FRRC) analysis TBA</a></li>
<li class="chapter" data-level="8.4.3" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-RRFCAnalysis"><i class="fa fa-check"></i><b>8.4.3</b> Random-reader fixed-case (RRFC) analysis</a></li>
<li class="chapter" data-level="8.4.4" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#roc-sample-size-dbm-STMRAnalysis"><i class="fa fa-check"></i><b>8.4.4</b> Single-treatment multiple-reader analysis</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="roc-sample-size-dbm.html"><a href="roc-sample-size-dbm.html#discussionsummary2"><i class="fa fa-check"></i><b>8.5</b> Discussion/Summary/2</a></li>
</ul></li>
<li class="part"><span><b>FROC analysis</b></span></li>
<li class="chapter" data-level="9" data-path="analyzing-froc-data.html"><a href="analyzing-froc-data.html"><i class="fa fa-check"></i><b>9</b> Analyzing FROC data</a>
<ul>
<li class="chapter" data-level="9.1" data-path="analyzing-froc-data.html"><a href="analyzing-froc-data.html#analyzing-froc-data-how-much-finished"><i class="fa fa-check"></i><b>9.1</b> TBA How much finished</a></li>
<li class="chapter" data-level="9.2" data-path="analyzing-froc-data.html"><a href="analyzing-froc-data.html#analyzing-froc-data-intro"><i class="fa fa-check"></i><b>9.2</b> Introduction</a></li>
<li class="chapter" data-level="9.3" data-path="analyzing-froc-data.html"><a href="analyzing-froc-data.html#analyzing-froc-data-example1"><i class="fa fa-check"></i><b>9.3</b> Example 1</a></li>
<li class="chapter" data-level="9.4" data-path="analyzing-froc-data.html"><a href="analyzing-froc-data.html#analyzing-froc-data-plotting"><i class="fa fa-check"></i><b>9.4</b> TBA Plotting wAFROC and ROC curves</a></li>
<li class="chapter" data-level="9.5" data-path="analyzing-froc-data.html"><a href="analyzing-froc-data.html#analyzing-froc-data-reporting"><i class="fa fa-check"></i><b>9.5</b> Reporting an FROC study</a></li>
<li class="chapter" data-level="9.6" data-path="analyzing-froc-data.html"><a href="analyzing-froc-data.html#crossed-treatment-analysis"><i class="fa fa-check"></i><b>9.6</b> Crossed-treatment analysis</a></li>
<li class="chapter" data-level="9.7" data-path="analyzing-froc-data.html"><a href="analyzing-froc-data.html#analyzing-froc-data-rjafroc-history"><i class="fa fa-check"></i><b>9.7</b> Discussion / Summary</a></li>
</ul></li>
<li class="part"><span><b>FROC sample size</b></span></li>
<li class="chapter" data-level="10" data-path="froc-sample-size.html"><a href="froc-sample-size.html"><i class="fa fa-check"></i><b>10</b> FROC sample size estimation</a>
<ul>
<li class="chapter" data-level="10.1" data-path="froc-sample-size.html"><a href="froc-sample-size.html#froc-sample-size-how-much-finished"><i class="fa fa-check"></i><b>10.1</b> How much finished 90 percent</a></li>
<li class="chapter" data-level="10.2" data-path="froc-sample-size.html"><a href="froc-sample-size.html#overview"><i class="fa fa-check"></i><b>10.2</b> Overview</a></li>
<li class="chapter" data-level="10.3" data-path="froc-sample-size.html"><a href="froc-sample-size.html#part-1"><i class="fa fa-check"></i><b>10.3</b> Part 1</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="froc-sample-size.html"><a href="froc-sample-size.html#froc-sample-size-intro"><i class="fa fa-check"></i><b>10.3.1</b> Introduction</a></li>
<li class="chapter" data-level="10.3.2" data-path="froc-sample-size.html"><a href="froc-sample-size.html#relating-roc-and-wafroc-effect-sizes"><i class="fa fa-check"></i><b>10.3.2</b> Relating ROC and wAFROC effect-sizes</a></li>
<li class="chapter" data-level="10.3.3" data-path="froc-sample-size.html"><a href="froc-sample-size.html#roc-and-wafroc-variance-components"><i class="fa fa-check"></i><b>10.3.3</b> ROC and wAFROC variance components</a></li>
<li class="chapter" data-level="10.3.4" data-path="froc-sample-size.html"><a href="froc-sample-size.html#roc-and-wafroc-power-for-equivalent-effect-sizes"><i class="fa fa-check"></i><b>10.3.4</b> ROC and wAFROC power for equivalent effect-sizes</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="froc-sample-size.html"><a href="froc-sample-size.html#part-2"><i class="fa fa-check"></i><b>10.4</b> Part 2</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="froc-sample-size.html"><a href="froc-sample-size.html#introduction"><i class="fa fa-check"></i><b>10.4.1</b> Introduction</a></li>
<li class="chapter" data-level="10.4.2" data-path="froc-sample-size.html"><a href="froc-sample-size.html#constructing-the-nh-model-for-the-dataset"><i class="fa fa-check"></i><b>10.4.2</b> Constructing the NH model for the dataset</a></li>
<li class="chapter" data-level="10.4.3" data-path="froc-sample-size.html"><a href="froc-sample-size.html#froc-sample-size-variance-components"><i class="fa fa-check"></i><b>10.4.3</b> Extract the wAFROC variance components</a></li>
<li class="chapter" data-level="10.4.4" data-path="froc-sample-size.html"><a href="froc-sample-size.html#wafroc-power-for-specified-roc-effect-size-number-of-readers-and-number-of-cases"><i class="fa fa-check"></i><b>10.4.4</b> wAFROC power for specified ROC effect size, number of readers and number of cases</a></li>
<li class="chapter" data-level="10.4.5" data-path="froc-sample-size.html"><a href="froc-sample-size.html#number-of-cases-for-80-percent-power-for-a-given-number-of-readers"><i class="fa fa-check"></i><b>10.4.5</b> Number of cases for 80 percent power for a given number of readers</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="froc-sample-size.html"><a href="froc-sample-size.html#part-3"><i class="fa fa-check"></i><b>10.5</b> Part 3</a>
<ul>
<li class="chapter" data-level="10.5.1" data-path="froc-sample-size.html"><a href="froc-sample-size.html#application-to-all-available-froc-datasets"><i class="fa fa-check"></i><b>10.5.1</b> Application to all available FROC datasets</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="froc-sample-size.html"><a href="froc-sample-size.html#discussion"><i class="fa fa-check"></i><b>10.6</b> Discussion</a></li>
</ul></li>
<li class="part"><span><b>Software details</b></span></li>
<li class="chapter" data-level="11" data-path="dataset-object-details.html"><a href="dataset-object-details.html"><i class="fa fa-check"></i><b>11</b> Excel file and dataset details</a>
<ul>
<li class="chapter" data-level="11.1" data-path="dataset-object-details.html"><a href="dataset-object-details.html#introduction-1"><i class="fa fa-check"></i><b>11.1</b> Introduction</a></li>
<li class="chapter" data-level="11.2" data-path="dataset-object-details.html"><a href="dataset-object-details.html#dataset-object-details-roc-dataset"><i class="fa fa-check"></i><b>11.2</b> ROC dataset</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="dataset-object-details.html"><a href="dataset-object-details.html#dataset-object-details-structure-roc-dataset"><i class="fa fa-check"></i><b>11.2.1</b> The structure of a factorial ROC dataset object</a></li>
<li class="chapter" data-level="11.2.2" data-path="dataset-object-details.html"><a href="dataset-object-details.html#dataset-object-details-read-datafile-correspondence-nl-fp"><i class="fa fa-check"></i><b>11.2.2</b> The <code>FP</code> worksheet</a></li>
<li class="chapter" data-level="11.2.3" data-path="dataset-object-details.html"><a href="dataset-object-details.html#dataset-object-details-read-datafile-correspondence-ll-tp"><i class="fa fa-check"></i><b>11.2.3</b> The <code>TP</code> worksheet</a></li>
<li class="chapter" data-level="11.2.4" data-path="dataset-object-details.html"><a href="dataset-object-details.html#dataset-object-details-read-datafile-correspondence-case-index-vs-case-id"><i class="fa fa-check"></i><b>11.2.4</b> caseIndex vs. caseID</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="dataset-object-details.html"><a href="dataset-object-details.html#dataset-object-details-froc-dataset"><i class="fa fa-check"></i><b>11.3</b> FROC dataset</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="dataset-object-details.html"><a href="dataset-object-details.html#dataset-object-details-structure-froc-dataset"><i class="fa fa-check"></i><b>11.3.1</b> The structure of a factorial FROC dataset</a></li>
<li class="chapter" data-level="11.3.2" data-path="dataset-object-details.html"><a href="dataset-object-details.html#dataset-object-truth-table-str"><i class="fa fa-check"></i><b>11.3.2</b> <code>truthTableStr</code></a></li>
<li class="chapter" data-level="11.3.3" data-path="dataset-object-details.html"><a href="dataset-object-details.html#the-fp-worksheet"><i class="fa fa-check"></i><b>11.3.3</b> The FP worksheet</a></li>
<li class="chapter" data-level="11.3.4" data-path="dataset-object-details.html"><a href="dataset-object-details.html#the-tp-worksheet"><i class="fa fa-check"></i><b>11.3.4</b> The TP worksheet</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>DATASETS</b></span></li>
<li class="chapter" data-level="12" data-path="datasets.html"><a href="datasets.html"><i class="fa fa-check"></i><b>12</b> Datasets</a>
<ul>
<li class="chapter" data-level="12.1" data-path="datasets.html"><a href="datasets.html#datasets-datasetsdd"><i class="fa fa-check"></i><b>12.1</b> Datasets embedded in <code>RJafroc</code></a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="datasets.html"><a href="datasets.html#datasets-dataset01"><i class="fa fa-check"></i><b>12.1.1</b> Dataset01</a></li>
<li class="chapter" data-level="12.1.2" data-path="datasets.html"><a href="datasets.html#datasets-dataset02"><i class="fa fa-check"></i><b>12.1.2</b> Dataset02</a></li>
<li class="chapter" data-level="12.1.3" data-path="datasets.html"><a href="datasets.html#datasets-dataset03"><i class="fa fa-check"></i><b>12.1.3</b> Dataset03</a></li>
<li class="chapter" data-level="12.1.4" data-path="datasets.html"><a href="datasets.html#datasets-dataset04"><i class="fa fa-check"></i><b>12.1.4</b> Dataset04</a></li>
<li class="chapter" data-level="12.1.5" data-path="datasets.html"><a href="datasets.html#datasets-dataset05"><i class="fa fa-check"></i><b>12.1.5</b> Dataset05</a></li>
<li class="chapter" data-level="12.1.6" data-path="datasets.html"><a href="datasets.html#datasets-dataset06"><i class="fa fa-check"></i><b>12.1.6</b> Dataset06</a></li>
<li class="chapter" data-level="12.1.7" data-path="datasets.html"><a href="datasets.html#datasets-dataset07"><i class="fa fa-check"></i><b>12.1.7</b> Dataset07</a></li>
<li class="chapter" data-level="12.1.8" data-path="datasets.html"><a href="datasets.html#datasets-dataset08"><i class="fa fa-check"></i><b>12.1.8</b> Dataset08</a></li>
<li class="chapter" data-level="12.1.9" data-path="datasets.html"><a href="datasets.html#datasets-dataset09"><i class="fa fa-check"></i><b>12.1.9</b> Dataset09</a></li>
<li class="chapter" data-level="12.1.10" data-path="datasets.html"><a href="datasets.html#datasets-dataset10"><i class="fa fa-check"></i><b>12.1.10</b> Dataset10</a></li>
<li class="chapter" data-level="12.1.11" data-path="datasets.html"><a href="datasets.html#datasets-dataset11"><i class="fa fa-check"></i><b>12.1.11</b> Dataset11</a></li>
<li class="chapter" data-level="12.1.12" data-path="datasets.html"><a href="datasets.html#datasets-dataset12"><i class="fa fa-check"></i><b>12.1.12</b> Dataset12</a></li>
<li class="chapter" data-level="12.1.13" data-path="datasets.html"><a href="datasets.html#datasets-dataset13"><i class="fa fa-check"></i><b>12.1.13</b> Dataset13</a></li>
<li class="chapter" data-level="12.1.14" data-path="datasets.html"><a href="datasets.html#datasets-dataset14"><i class="fa fa-check"></i><b>12.1.14</b> Dataset14</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="datasets.html"><a href="datasets.html#other-datasets"><i class="fa fa-check"></i><b>12.2</b> Other datasets</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="datasets.html"><a href="datasets.html#datasets-datasetCadLroc"><i class="fa fa-check"></i><b>12.2.1</b> DatasetCadLroc</a></li>
<li class="chapter" data-level="12.2.2" data-path="datasets.html"><a href="datasets.html#datasets-datasetCadSimuFroc"><i class="fa fa-check"></i><b>12.2.2</b> datasetCadSimuFroc</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>REFERENCES</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">The RJafroc Quick Start Book</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="froc-sample-size" class="section level1 hasAnchor" number="10">
<h1><span class="header-section-number">Chapter 10</span> FROC sample size estimation<a href="froc-sample-size.html#froc-sample-size" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="froc-sample-size-how-much-finished" class="section level2 hasAnchor" number="10.1">
<h2><span class="header-section-number">10.1</span> How much finished 90 percent<a href="froc-sample-size.html#froc-sample-size-how-much-finished" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Comments on reason for increased FROC power; discuss idea about separating treatments and using lower half in terms of AUC to compute the NH parameters; does this improve DOBBINS-1 performance - solve the unusually low scale factor for this dataset?</p>
</div>
<div id="overview" class="section level2 hasAnchor" number="10.2">
<h2><span class="header-section-number">10.2</span> Overview<a href="froc-sample-size.html#overview" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This chapter is split into three parts:</p>
<ul>
<li><p>Part 1 is a step-by-step approach to FROC paradigm sample size estimation;</p></li>
<li><p>Part 2 encapsulates some of the details in <code>SsFrocNhRsmModel()</code>.</p></li>
<li><p>Part 3 uses <code>SsFrocSampleSize()</code> which simplifies the procedure to a single function call and applies it to 7 FROC datasets.</p></li>
</ul>
</div>
<div id="part-1" class="section level2 hasAnchor" number="10.3">
<h2><span class="header-section-number">10.3</span> Part 1<a href="froc-sample-size.html#part-1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="froc-sample-size-intro" class="section level3 hasAnchor" number="10.3.1">
<h3><span class="header-section-number">10.3.1</span> Introduction<a href="froc-sample-size.html#froc-sample-size-intro" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>FROC sample size estimation is not fundamentally different from ROC sample size estimation, Chapter <a href="roc-sample-size-dbm.html#roc-sample-size-dbm">8</a>.</p>
<p><strong>A recapitulation of ROC sample size estimation</strong></p>
<p>Based on analysis of a pilot ROC dataset and using a specified figure of merit (FOM), e.g., <code>FOM = Wilcoxon</code>, and either <code>method = "DBM"</code> or <code>method = "OR"</code> for significance testing, one estimates the intrinsic variability of the data expressed in terms of FOM variance components. For the DBM method these are the pseudovalue-based variance components while for OR method these are the FOM-based variance and covariances. <strong>In this chapter the OR variance components will be used.</strong> The second step is to specify a clinically realistic effect-size, e.g., the anticipated AUC difference between the two modalities.</p>
<p>Given the variance components and the anticipated AUC difference the sample size functions (<code>RJafroc</code> function names beginning with <code>Ss</code>) allow one to estimate the number of readers and cases necessary to detect (i.e., reject the null hypothesis) the modality AUC difference with probability <span class="math inline">\(\beta\)</span>, typically chosen to be 20 percent (corresponding to 80 percent statistical power) while maintaining the NH (zero AUC difference) rejection rate probability at <span class="math inline">\(\alpha\)</span>, typically chosen to be 5 percent.</p>
<p><strong>Summary of FROC sample size estimation</strong></p>
<p>In FROC analysis the only difference, indeed the critical difference, is the choice of FOM; e.g., <code>FOM = "wAFROC"</code> instead of the ROC-AUC, <code>FOM = "Wilcoxon"</code>. The FROC dataset is analyzed using the DBM (or the OR) method. This yields the necessary variance components (or the covariance matrix) of the wAFROC-AUC. Next one specifies the effect-size <strong>in wAFROC-AUC units</strong> and this requires care. The ROC-AUC has a historically well-known interpretation, namely it is the classification ability at separating diseased patients from non-diseased patients, while the wAFROC-AUC does not. Needed is a way of relating the effect-size in easily understood ROC-AUC units to one in wAFROC-AUC units. This requires a physical model, e.g., the RSM, that predicts both ROC and wAFROC curves and their corresponding AUCs.</p>
<ol style="list-style-type: decimal">
<li><p>One chooses an ROC-AUC effect-size that is realistic, one that clinicians understand and can therefore participate in, in the effect-size postulation process. Lacking such information I recommend, based on past ROC studies, 0.03 as typical of a small effect size and 0.05 as typical of a moderate effect size.</p></li>
<li><p>One converts the ROC effect-size to a wAFROC-AUC effect-size using the method described in the next section.</p></li>
<li><p>One uses the sample size tools in <code>RJafroc</code> to determine sample size for a desired statistical power.</p></li>
</ol>
<blockquote>
<p><strong>It is important to recognize is that all quantities have to be in the same units</strong>. When performing ROC analysis, everything (variance components and effect-size) has to be in units of the selected FOM, e.g., <code>FOM = "Wilcoxon"</code>. When doing wAFROC analysis, everything has to be in units of the wAFROC-AUC, i.e., <code>FOM = "wAFROC"</code>. The variance components and effect-size in wAFROC-AUC units will be different from their corresponding ROC counterparts. In particular, as shown next, an ROC-AUC effect-size of 0.05 generally corresponds to a larger effect-size in wAFROC-AUC units. The reason for this is that the range over which wAFROC-AUC can vary, namely 0 to 1, is twice the corresponding ROC-AUC range (0.5 to 1). For the same reason the wAFROC variance components also tend to be larger than the ROC variance components.</p>
</blockquote>
<p>The next section explains the steps used to implement #2 above.</p>
</div>
<div id="relating-roc-and-wafroc-effect-sizes" class="section level3 hasAnchor" number="10.3.2">
<h3><span class="header-section-number">10.3.2</span> Relating ROC and wAFROC effect-sizes<a href="froc-sample-size.html#relating-roc-and-wafroc-effect-sizes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The steps are illustrated using <code>dataset04</code>, a 5 treatment, 4 radiologist and 200 case FROC dataset <span class="citation">(<a href="#ref-zanca2009evaluation" role="doc-biblioref">Zanca et al. 2009</a>)</span> acquired on a 5-point scale, i.e., the data is already binned. If not binned one needs to bin the dataset using <code>DfBinDataset()</code> before RSM fitting can be performed.</p>
<p>The following code computes <code>JStar</code> and <code>KStar</code>, the numbers of readers and cases in the pilot dataset. These are needed below for correct scaling of the OR variance components.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="froc-sample-size.html#cb37-1" aria-hidden="true" tabindex="-1"></a>JStar <span class="ot">&lt;-</span> <span class="fu">length</span>(dataset04<span class="sc">$</span>ratings<span class="sc">$</span>NL[<span class="dv">1</span>,,<span class="dv">1</span>,<span class="dv">1</span>])</span>
<span id="cb37-2"><a href="froc-sample-size.html#cb37-2" aria-hidden="true" tabindex="-1"></a>KStar <span class="ot">&lt;-</span> <span class="fu">length</span>(dataset04<span class="sc">$</span>ratings<span class="sc">$</span>NL[<span class="dv">1</span>,<span class="dv">1</span>,,<span class="dv">1</span>])</span></code></pre></div>
<div id="extract-nh-treatments" class="section level4 hasAnchor" number="10.3.2.1">
<h4><span class="header-section-number">10.3.2.1</span> Extract NH treatments<a href="froc-sample-size.html#extract-nh-treatments" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>If there are more than two treatments in the pilot dataset, as in <code>dataset04</code>, one extracts those treatments that represent “almost” null hypothesis data (in the sense of similar ROC-AUCs):</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="froc-sample-size.html#cb38-1" aria-hidden="true" tabindex="-1"></a>frocDataNH <span class="ot">&lt;-</span> <span class="fu">DfExtractDataset</span>(dataset04, <span class="at">trts =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span></code></pre></div>
<p>extracts treatments 1 and 2. These treatments were found <span class="citation">(<a href="#ref-zanca2009evaluation" role="doc-biblioref">Zanca et al. 2009</a>)</span> to be “almost” equivalent (the NH could not be rejected for the wAFROC-AUC difference between these treatments). More than two treatments can be used if they have similar AUCs, as this will improve the stability of the procedure. However, the final sample size predictions are restricted to two treatments in the pivotal study.</p>
<p>The next two steps are needed since <strong>the RSM can only fit binned ROC data</strong>.</p>
</div>
<div id="convert-the-froc-nh-data-to-roc" class="section level4 hasAnchor" number="10.3.2.2">
<h4><span class="header-section-number">10.3.2.2</span> Convert the FROC NH data to ROC<a href="froc-sample-size.html#convert-the-froc-nh-data-to-roc" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>If the original data is FROC, one converts it to ROC:</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="froc-sample-size.html#cb39-1" aria-hidden="true" tabindex="-1"></a>rocDataNH <span class="ot">&lt;-</span> <span class="fu">DfFroc2Roc</span>(frocDataNH)</span></code></pre></div>
</div>
<div id="bin-the-data" class="section level4 hasAnchor" number="10.3.2.3">
<h4><span class="header-section-number">10.3.2.3</span> Bin the data<a href="froc-sample-size.html#bin-the-data" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>If the NH dataset uses continuous ratings one bins the ratings:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="froc-sample-size.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># For dataset04 this is unnecessary as it is already binned but it can&#39;t hurt</span></span>
<span id="cb40-2"><a href="froc-sample-size.html#cb40-2" aria-hidden="true" tabindex="-1"></a>rocDataBinNH <span class="ot">&lt;-</span> <span class="fu">DfBinDataset</span>(rocDataNH, <span class="at">opChType =</span> <span class="st">&quot;ROC&quot;</span>)</span></code></pre></div>
<p>The default number of bins should be used. Unlike binning using arbitrarily set thresholds the thresholds found by <code>DfBinDataset()</code> are unique as they maximize the empirical ROC-AUC.</p>
</div>
<div id="determine-the-lesion-distribution-and-weights-of-the-froc-dataset" class="section level4 hasAnchor" number="10.3.2.4">
<h4><span class="header-section-number">10.3.2.4</span> Determine the lesion distribution and weights of the FROC dataset<a href="froc-sample-size.html#determine-the-lesion-distribution-and-weights-of-the-froc-dataset" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><code>lesDistr</code> is the lesion distribution, see Section <a href="quick-start-froc-data-format.html#quick-start-froc-data-lesion-distribution">3.7.1</a> and line 1 of the following code. The RSM fitting algorithm needs to know how lesion-rich the dataset is as the predicted ROC-AUC depends it. For this dataset fraction 0.69 of diseased cases have one lesion, fraction 0.2 have two lesions and fraction 0.11 have three lesions. One also needs the lesion weights matrix, <span class="math inline">\(\textbf{W}\)</span>, see Section <a href="quick-start-froc-data-format.html#quick-start-froc-data-lesion-weights">3.8</a>. The call at line 2 to <code>UtilLesWghtsDS</code> uses the default argument <code>relWeights = 0</code> which assigns equal weights to all lesions.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb41-1"><a href="froc-sample-size.html#cb41-1"></a>lesDistr <span class="ot">&lt;-</span> <span class="fu">UtilLesDistr</span>(frocDataNH)</span>
<span id="cb41-2"><a href="froc-sample-size.html#cb41-2"></a>W <span class="ot">&lt;-</span> <span class="fu">UtilLesWghtsDS</span>(frocDataNH)</span>
<span id="cb41-3"><a href="froc-sample-size.html#cb41-3"></a>W</span></code></pre></div>
<pre><code>##      [,1]      [,2]      [,3]      [,4]
## [1,]    1 1.0000000      -Inf      -Inf
## [2,]    2 0.5000000 0.5000000      -Inf
## [3,]    3 0.3333333 0.3333333 0.3333333</code></pre>
<p>Note that <code>lesDistr</code> and <span class="math inline">\(\textbf{W}\)</span> are determined from the <em>FROC</em> NH dataset as this information is lost upon conversion to an ROC dataset.</p>
</div>
<div id="fit-the-rsm-to-the-roc-data" class="section level4 hasAnchor" number="10.3.2.5">
<h4><span class="header-section-number">10.3.2.5</span> Fit the RSM to the ROC data<a href="froc-sample-size.html#fit-the-rsm-to-the-roc-data" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>For each treatment and reader the fitting algorithm <code>FitRsmRoc()</code> is applied (lines 4 - 11) to the binned NH ROC dataset. The returned values are <code>mu</code>, <code>lambda</code> and <code>nu</code>, corresponding to the physical RSM parameters <span class="math inline">\({\mu}\)</span>, <span class="math inline">\({\lambda}\)</span> and <span class="math inline">\({\nu}\)</span>.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb43-1"><a href="froc-sample-size.html#cb43-1"></a>I <span class="ot">&lt;-</span> <span class="fu">dim</span>(rocDataBinNH<span class="sc">$</span>ratings<span class="sc">$</span>NL)[<span class="dv">1</span>]</span>
<span id="cb43-2"><a href="froc-sample-size.html#cb43-2"></a>J <span class="ot">&lt;-</span> <span class="fu">dim</span>(rocDataBinNH<span class="sc">$</span>ratings<span class="sc">$</span>NL)[<span class="dv">2</span>]</span>
<span id="cb43-3"><a href="froc-sample-size.html#cb43-3"></a>RsmParmsNH <span class="ot">&lt;-</span> <span class="fu">array</span>(<span class="at">dim =</span> <span class="fu">c</span>(I,J,<span class="dv">3</span>))</span>
<span id="cb43-4"><a href="froc-sample-size.html#cb43-4"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>I) {</span>
<span id="cb43-5"><a href="froc-sample-size.html#cb43-5"></a>  <span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>J)  {</span>
<span id="cb43-6"><a href="froc-sample-size.html#cb43-6"></a>    fit <span class="ot">&lt;-</span> <span class="fu">FitRsmRoc</span>(rocDataBinNH, <span class="at">trt =</span> i, <span class="at">rdr =</span> j, lesDistr<span class="sc">$</span>Freq)</span>
<span id="cb43-7"><a href="froc-sample-size.html#cb43-7"></a>    RsmParmsNH[i,j,<span class="dv">1</span>] <span class="ot">&lt;-</span> fit[[<span class="dv">1</span>]] <span class="co"># mu</span></span>
<span id="cb43-8"><a href="froc-sample-size.html#cb43-8"></a>    RsmParmsNH[i,j,<span class="dv">2</span>] <span class="ot">&lt;-</span> fit[[<span class="dv">2</span>]] <span class="co"># lambda</span></span>
<span id="cb43-9"><a href="froc-sample-size.html#cb43-9"></a>    RsmParmsNH[i,j,<span class="dv">3</span>] <span class="ot">&lt;-</span> fit[[<span class="dv">3</span>]] <span class="co"># nu</span></span>
<span id="cb43-10"><a href="froc-sample-size.html#cb43-10"></a>  }</span>
<span id="cb43-11"><a href="froc-sample-size.html#cb43-11"></a>}</span></code></pre></div>
</div>
<div id="compute-the-median-values-of-the-rsm-parameters" class="section level4 hasAnchor" number="10.3.2.6">
<h4><span class="header-section-number">10.3.2.6</span> Compute the median values of the RSM parameters<a href="froc-sample-size.html#compute-the-median-values-of-the-rsm-parameters" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>I recommend taking the median (not the mean) of each of the parameters as representing the “average” NH dataset. The median is less sensitive to outliers than the mean.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="froc-sample-size.html#cb44-1" aria-hidden="true" tabindex="-1"></a>muNH <span class="ot">&lt;-</span> <span class="fu">median</span>(RsmParmsNH[,,<span class="dv">1</span>]) </span>
<span id="cb44-2"><a href="froc-sample-size.html#cb44-2" aria-hidden="true" tabindex="-1"></a>lambdaNH <span class="ot">&lt;-</span> <span class="fu">median</span>(RsmParmsNH[,,<span class="dv">2</span>])</span>
<span id="cb44-3"><a href="froc-sample-size.html#cb44-3" aria-hidden="true" tabindex="-1"></a>nuNH <span class="ot">&lt;-</span> <span class="fu">median</span>(RsmParmsNH[,,<span class="dv">3</span>])</span></code></pre></div>
<p>The defining values of the NH fitting model are <code>muNH</code> = 3.3121519, <code>lambdaNH</code> = 1.714368 and <code>nuNH</code> = 0.7036564.</p>
</div>
<div id="compute-roc-and-wafroc-nh-aucs" class="section level4 hasAnchor" number="10.3.2.7">
<h4><span class="header-section-number">10.3.2.7</span> Compute ROC and wAFROC NH AUCs<a href="froc-sample-size.html#compute-roc-and-wafroc-nh-aucs" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="froc-sample-size.html#cb45-1" aria-hidden="true" tabindex="-1"></a>aucRocNH <span class="ot">&lt;-</span> <span class="fu">UtilAnalyticalAucsRSM</span>(muNH, lambdaNH, nuNH, <span class="at">lesDistr =</span> lesDistr<span class="sc">$</span>Freq)<span class="sc">$</span>aucROC</span>
<span id="cb45-2"><a href="froc-sample-size.html#cb45-2" aria-hidden="true" tabindex="-1"></a>aucwAfrocNH <span class="ot">&lt;-</span> <span class="fu">UtilAnalyticalAucsRSM</span>(muNH, lambdaNH, nuNH, <span class="at">lesDistr =</span> lesDistr<span class="sc">$</span>Freq)<span class="sc">$</span>aucwAFROC</span></code></pre></div>
<p>The AUCs are: <code>aucRocNH = 0.8791542</code> and <code>aucwAfrocNH = 0.7198615</code>. Note that the wAFROC-FOM is smaller than the ROC-FOM as it includes detection and localization performance.</p>
</div>
<div id="compute-roc-and-wafroc-ah-aucs-for-a-range-of-roc-auc-effect-sizes" class="section level4 hasAnchor" number="10.3.2.8">
<h4><span class="header-section-number">10.3.2.8</span> Compute ROC and wAFROC AH AUCs for a range of ROC-AUC effect sizes<a href="froc-sample-size.html#compute-roc-and-wafroc-ah-aucs-for-a-range-of-roc-auc-effect-sizes" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>To define the alternative hypothesis (AH) condition, one increments <span class="math inline">\(\mu_{NH}\)</span> by <span class="math inline">\(\Delta_{\mu}\)</span>. It is not enough to simply increase the <span class="math inline">\(\mu\)</span> parameter as increasing it simultaneously decreases <span class="math inline">\(\lambda\)</span> and increase <span class="math inline">\(\nu\)</span>. To account for this one extracts the intrinsic parameters <span class="math inline">\(\lambda_i, \nu_i\)</span> at line 7 and then converts back to the physical parameters at line 9 using the incremented <span class="math inline">\(\mu\)</span>. Note the usage of the functions The resulting ROC-AUC and wAFROC-AUC are calculated. One calculates the effect size (AH value minus NH value) using ROC and wAFROC FOMs for a series of specified <code>deltaMu</code> values. This generates values that can be used to relate the wAFROC effect size for a specified ROC effect size.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb46-1"><a href="froc-sample-size.html#cb46-1"></a>deltaMu <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.01</span>, <span class="fl">0.2</span>, <span class="fl">0.01</span>)</span>
<span id="cb46-2"><a href="froc-sample-size.html#cb46-2"></a>esROC <span class="ot">&lt;-</span> <span class="fu">array</span>(<span class="at">dim =</span> <span class="fu">length</span>(deltaMu))</span>
<span id="cb46-3"><a href="froc-sample-size.html#cb46-3"></a>eswAFROC <span class="ot">&lt;-</span> <span class="fu">array</span>(<span class="at">dim =</span> <span class="fu">length</span>(deltaMu))</span>
<span id="cb46-4"><a href="froc-sample-size.html#cb46-4"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(deltaMu)) {</span>
<span id="cb46-5"><a href="froc-sample-size.html#cb46-5"></a>  </span>
<span id="cb46-6"><a href="froc-sample-size.html#cb46-6"></a>  <span class="co"># get intrinsic parameters</span></span>
<span id="cb46-7"><a href="froc-sample-size.html#cb46-7"></a>  par_i <span class="ot">&lt;-</span> <span class="fu">Util2Intrinsic</span>(muNH, lambdaNH, nuNH) <span class="co"># intrinsic</span></span>
<span id="cb46-8"><a href="froc-sample-size.html#cb46-8"></a>  <span class="co"># find physical parameters for increased muNH accounting for combined change</span></span>
<span id="cb46-9"><a href="froc-sample-size.html#cb46-9"></a>  par_p <span class="ot">&lt;-</span> <span class="fu">Util2Physical</span>(muNH <span class="sc">+</span> deltaMu[i], par_i<span class="sc">$</span>lambda_i, par_i<span class="sc">$</span>nu_i)  <span class="co"># physical</span></span>
<span id="cb46-10"><a href="froc-sample-size.html#cb46-10"></a>  </span>
<span id="cb46-11"><a href="froc-sample-size.html#cb46-11"></a>  esROC[i] <span class="ot">&lt;-</span> <span class="fu">UtilAnalyticalAucsRSM</span>(</span>
<span id="cb46-12"><a href="froc-sample-size.html#cb46-12"></a>    muNH <span class="sc">+</span> deltaMu[i], par_p<span class="sc">$</span>lambda, par_p<span class="sc">$</span>nu, <span class="at">lesDistr =</span> lesDistr<span class="sc">$</span>Freq)<span class="sc">$</span>aucROC <span class="sc">-</span> aucRocNH</span>
<span id="cb46-13"><a href="froc-sample-size.html#cb46-13"></a>  </span>
<span id="cb46-14"><a href="froc-sample-size.html#cb46-14"></a>  eswAFROC[i] <span class="ot">&lt;-</span> <span class="fu">UtilAnalyticalAucsRSM</span>(</span>
<span id="cb46-15"><a href="froc-sample-size.html#cb46-15"></a>    muNH <span class="sc">+</span> deltaMu[i], par_p<span class="sc">$</span>lambda, par_p<span class="sc">$</span>nu, <span class="at">lesDistr =</span> lesDistr<span class="sc">$</span>Freq)<span class="sc">$</span>aucwAFROC <span class="sc">-</span> aucwAfrocNH</span>
<span id="cb46-16"><a href="froc-sample-size.html#cb46-16"></a>  </span>
<span id="cb46-17"><a href="froc-sample-size.html#cb46-17"></a>}</span></code></pre></div>
<p>Here is a plot of wAFROC effect size (y-axis) vs. ROC effect size.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-12"></span>
<img src="19-froc-sample-size_files/figure-html/unnamed-chunk-12-1.png" alt="Plot of wAFROC effect size vs. ROC effect size. The straight line fit through the origin has slope 2.169." width="672" />
<p class="caption">
FIGURE 10.1: Plot of wAFROC effect size vs. ROC effect size. The straight line fit through the origin has slope 2.169.
</p>
</div>
<p>The plot is linear and the intercept is close to zero. This makes it easy to implement an interpolation function. In the following code line 1 fits <code>eswAFROC</code> vs. <code>esROC</code> using a linear model <code>lm()</code> function constrained to pass through the origin (the “-1”). One expects this constraint since for <code>deltaMu = 0</code> the effect size must be zero no matter how it is measured.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb47-1"><a href="froc-sample-size.html#cb47-1"></a>scaleFactor <span class="ot">&lt;-</span> <span class="fu">lm</span>(eswAFROC <span class="sc">~</span> <span class="sc">-</span><span class="dv">1</span> <span class="sc">+</span> esROC) <span class="co"># the &quot;-1&quot; fits to straight line through the origin</span></span>
<span id="cb47-2"><a href="froc-sample-size.html#cb47-2"></a>effectSizeROC <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="fl">0.01</span>, <span class="fl">0.0525</span>, <span class="fl">0.0025</span>) </span>
<span id="cb47-3"><a href="froc-sample-size.html#cb47-3"></a>effectSizewAFROC <span class="ot">&lt;-</span> effectSizeROC<span class="sc">*</span>scaleFactor<span class="sc">$</span>coefficients[<span class="dv">1</span>]</span></code></pre></div>
<p>The slope of the zero-intercept constrained straight line fit is <code>scaleFactor</code> = 2.169 and the squared correlation coefficient is <code>R2</code> = 0.9999904 (the fit is very good). Therefore, the conversion from ROC to wAFROC effect size is:</p>
<pre><code>effectSizewAFROC = scaleFactor * effectSizeROC</code></pre>
<p><strong>For this dataset the wAFROC effect size is 2.169 times the ROC effect size.</strong> The wAFROC effect size is expected to be larger than the ROC effect size because the range of wAFROC-AUC, <span class="math inline">\(1-0=1\)</span>, is twice that of ROC-AUC, <span class="math inline">\(1-0.5=0.5\)</span>.</p>
</div>
</div>
<div id="roc-and-wafroc-variance-components" class="section level3 hasAnchor" number="10.3.3">
<h3><span class="header-section-number">10.3.3</span> ROC and wAFROC variance components<a href="froc-sample-size.html#roc-and-wafroc-variance-components" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The following skeleton code shows the arguments of the function <code>UtilVarComponentsOR</code> used to calculate the OR variance components.</p>
<pre><code>UtilVarComponentsOR(
  dataset,
  FOM,
  FPFValue = 0.2,
  covEstMethod = &quot;jackknife&quot;,
  nBoots = 200,
  seed = NULL
)</code></pre>
<p><code>UtilVarComponentsOR()</code> is applied to <code>rocDataNH</code> and <code>frocDataNH</code> (using “Wilcoxon” and “wAFROC” FOMs respectively) followed by the extraction of the two OR variance components.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb50-1"><a href="froc-sample-size.html#cb50-1"></a>varComp_roc <span class="ot">&lt;-</span> <span class="fu">UtilVarComponentsOR</span>(</span>
<span id="cb50-2"><a href="froc-sample-size.html#cb50-2"></a>  rocDataNH, </span>
<span id="cb50-3"><a href="froc-sample-size.html#cb50-3"></a>  <span class="at">FOM =</span> <span class="st">&quot;Wilcoxon&quot;</span>)<span class="sc">$</span>VarCom[<span class="sc">-</span><span class="dv">2</span>]</span>
<span id="cb50-4"><a href="froc-sample-size.html#cb50-4"></a></span>
<span id="cb50-5"><a href="froc-sample-size.html#cb50-5"></a>varComp_wafroc <span class="ot">&lt;-</span> <span class="fu">UtilVarComponentsOR</span>(</span>
<span id="cb50-6"><a href="froc-sample-size.html#cb50-6"></a>  frocDataNH, </span>
<span id="cb50-7"><a href="froc-sample-size.html#cb50-7"></a>  <span class="at">FOM =</span> <span class="st">&quot;wAFROC&quot;</span>)<span class="sc">$</span>VarCom[<span class="sc">-</span><span class="dv">2</span>]</span></code></pre></div>
<p>VarCom[-2] removes the second column of each dataframe containing the correlations. The ROC and wAFROC variance components are:</p>
<pre><code>##                ROC        wAFROC
## VarR  0.0008277380  0.0018542289
## VarTR 0.0001526507 -0.0004439279
## Cov1  0.0002083377  0.0003736844
## Cov2  0.0002388384  0.0003567162
## Cov3  0.0001906167  0.0003058902
## Var   0.0007307912  0.0009081383</code></pre>
</div>
<div id="roc-and-wafroc-power-for-equivalent-effect-sizes" class="section level3 hasAnchor" number="10.3.4">
<h3><span class="header-section-number">10.3.4</span> ROC and wAFROC power for equivalent effect-sizes<a href="froc-sample-size.html#roc-and-wafroc-power-for-equivalent-effect-sizes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We compare ROC and wAFROC random-reader random-case (RRRC) powers for equivalent effect sizes.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb52-1"><a href="froc-sample-size.html#cb52-1"></a><span class="co"># these are OR variance components assuming FOM = &quot;Wilcoxon&quot;</span></span>
<span id="cb52-2"><a href="froc-sample-size.html#cb52-2"></a>varR_roc <span class="ot">&lt;-</span> varComp_roc[<span class="st">&quot;VarR&quot;</span>,<span class="st">&quot;Estimates&quot;</span>]</span>
<span id="cb52-3"><a href="froc-sample-size.html#cb52-3"></a>varTR_roc <span class="ot">&lt;-</span> varComp_roc[<span class="st">&quot;VarTR&quot;</span>,<span class="st">&quot;Estimates&quot;</span>]</span>
<span id="cb52-4"><a href="froc-sample-size.html#cb52-4"></a>Cov1_roc <span class="ot">&lt;-</span> varComp_roc[<span class="st">&quot;Cov1&quot;</span>,<span class="st">&quot;Estimates&quot;</span>]</span>
<span id="cb52-5"><a href="froc-sample-size.html#cb52-5"></a>Cov2_roc <span class="ot">&lt;-</span> varComp_roc[<span class="st">&quot;Cov2&quot;</span>,<span class="st">&quot;Estimates&quot;</span>]</span>
<span id="cb52-6"><a href="froc-sample-size.html#cb52-6"></a>Cov3_roc <span class="ot">&lt;-</span> varComp_roc[<span class="st">&quot;Cov3&quot;</span>,<span class="st">&quot;Estimates&quot;</span>]</span>
<span id="cb52-7"><a href="froc-sample-size.html#cb52-7"></a>Var_roc <span class="ot">&lt;-</span> varComp_roc[<span class="st">&quot;Var&quot;</span>,<span class="st">&quot;Estimates&quot;</span>]</span>
<span id="cb52-8"><a href="froc-sample-size.html#cb52-8"></a></span>
<span id="cb52-9"><a href="froc-sample-size.html#cb52-9"></a><span class="co"># these are OR variance components assuming FOM = &quot;wAFROC&quot;</span></span>
<span id="cb52-10"><a href="froc-sample-size.html#cb52-10"></a>varR_wafroc <span class="ot">&lt;-</span> varComp_wafroc[<span class="st">&quot;VarR&quot;</span>,<span class="st">&quot;Estimates&quot;</span>]</span>
<span id="cb52-11"><a href="froc-sample-size.html#cb52-11"></a>varTR_wafroc <span class="ot">&lt;-</span> varComp_wafroc[<span class="st">&quot;VarTR&quot;</span>,<span class="st">&quot;Estimates&quot;</span>]</span>
<span id="cb52-12"><a href="froc-sample-size.html#cb52-12"></a>Cov1_wafroc <span class="ot">&lt;-</span> varComp_wafroc[<span class="st">&quot;Cov1&quot;</span>,<span class="st">&quot;Estimates&quot;</span>]</span>
<span id="cb52-13"><a href="froc-sample-size.html#cb52-13"></a>Cov2_wafroc <span class="ot">&lt;-</span> varComp_wafroc[<span class="st">&quot;Cov2&quot;</span>,<span class="st">&quot;Estimates&quot;</span>]</span>
<span id="cb52-14"><a href="froc-sample-size.html#cb52-14"></a>Cov3_wafroc <span class="ot">&lt;-</span> varComp_wafroc[<span class="st">&quot;Cov3&quot;</span>,<span class="st">&quot;Estimates&quot;</span>]</span>
<span id="cb52-15"><a href="froc-sample-size.html#cb52-15"></a>Var_wafroc <span class="ot">&lt;-</span> varComp_wafroc[<span class="st">&quot;Var&quot;</span>,<span class="st">&quot;Estimates&quot;</span>]</span>
<span id="cb52-16"><a href="froc-sample-size.html#cb52-16"></a></span>
<span id="cb52-17"><a href="froc-sample-size.html#cb52-17"></a>power_roc <span class="ot">&lt;-</span> <span class="fu">array</span>(<span class="at">dim =</span> <span class="fu">length</span>(effectSizeROC))</span>
<span id="cb52-18"><a href="froc-sample-size.html#cb52-18"></a>power_wafroc <span class="ot">&lt;-</span> <span class="fu">array</span>(<span class="at">dim =</span> <span class="fu">length</span>(effectSizeROC))</span>
<span id="cb52-19"><a href="froc-sample-size.html#cb52-19"></a></span>
<span id="cb52-20"><a href="froc-sample-size.html#cb52-20"></a>JPivot <span class="ot">&lt;-</span> <span class="dv">5</span>;KPivot <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb52-21"><a href="froc-sample-size.html#cb52-21"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(effectSizeROC)) {</span>
<span id="cb52-22"><a href="froc-sample-size.html#cb52-22"></a>  </span>
<span id="cb52-23"><a href="froc-sample-size.html#cb52-23"></a>  <span class="co"># compute ROC power</span></span>
<span id="cb52-24"><a href="froc-sample-size.html#cb52-24"></a>  ret <span class="ot">&lt;-</span> <span class="fu">SsPowerGivenJK</span>(</span>
<span id="cb52-25"><a href="froc-sample-size.html#cb52-25"></a>    <span class="at">dataset =</span> <span class="cn">NULL</span>, </span>
<span id="cb52-26"><a href="froc-sample-size.html#cb52-26"></a>    <span class="at">FOM =</span> <span class="st">&quot;Wilcoxon&quot;</span>, </span>
<span id="cb52-27"><a href="froc-sample-size.html#cb52-27"></a>    <span class="at">J =</span> JPivot, </span>
<span id="cb52-28"><a href="froc-sample-size.html#cb52-28"></a>    <span class="at">K =</span> KPivot, </span>
<span id="cb52-29"><a href="froc-sample-size.html#cb52-29"></a>    <span class="at">effectSize =</span> effectSizeROC[i], </span>
<span id="cb52-30"><a href="froc-sample-size.html#cb52-30"></a>    <span class="fu">list</span>(<span class="at">JStar =</span> JStar, <span class="at">KStar =</span> KStar, </span>
<span id="cb52-31"><a href="froc-sample-size.html#cb52-31"></a>         <span class="at">VarTR =</span> varTR_roc,</span>
<span id="cb52-32"><a href="froc-sample-size.html#cb52-32"></a>         <span class="at">Cov1 =</span> Cov1_roc,</span>
<span id="cb52-33"><a href="froc-sample-size.html#cb52-33"></a>         <span class="at">Cov2 =</span> Cov2_roc,</span>
<span id="cb52-34"><a href="froc-sample-size.html#cb52-34"></a>         <span class="at">Cov3 =</span> Cov3_roc,</span>
<span id="cb52-35"><a href="froc-sample-size.html#cb52-35"></a>         <span class="at">Var =</span> Var_roc))</span>
<span id="cb52-36"><a href="froc-sample-size.html#cb52-36"></a>  power_roc[i] <span class="ot">&lt;-</span> ret<span class="sc">$</span>powerRRRC</span>
<span id="cb52-37"><a href="froc-sample-size.html#cb52-37"></a>  </span>
<span id="cb52-38"><a href="froc-sample-size.html#cb52-38"></a>  <span class="co"># compute wAFROC power</span></span>
<span id="cb52-39"><a href="froc-sample-size.html#cb52-39"></a>  ret <span class="ot">&lt;-</span> <span class="fu">SsPowerGivenJK</span>(</span>
<span id="cb52-40"><a href="froc-sample-size.html#cb52-40"></a>    <span class="at">dataset =</span> <span class="cn">NULL</span>, </span>
<span id="cb52-41"><a href="froc-sample-size.html#cb52-41"></a>    <span class="at">FOM =</span> <span class="st">&quot;wAFROC&quot;</span>, </span>
<span id="cb52-42"><a href="froc-sample-size.html#cb52-42"></a>    <span class="at">J =</span> JPivot, </span>
<span id="cb52-43"><a href="froc-sample-size.html#cb52-43"></a>    <span class="at">K =</span> KPivot, </span>
<span id="cb52-44"><a href="froc-sample-size.html#cb52-44"></a>    <span class="at">effectSize =</span> effectSizewAFROC[i], </span>
<span id="cb52-45"><a href="froc-sample-size.html#cb52-45"></a>    <span class="fu">list</span>(<span class="at">JStar =</span> JStar, <span class="at">KStar =</span> KStar, </span>
<span id="cb52-46"><a href="froc-sample-size.html#cb52-46"></a>         <span class="at">VarTR =</span> varTR_wafroc,</span>
<span id="cb52-47"><a href="froc-sample-size.html#cb52-47"></a>         <span class="at">Cov1 =</span> Cov1_wafroc,</span>
<span id="cb52-48"><a href="froc-sample-size.html#cb52-48"></a>         <span class="at">Cov2 =</span> Cov2_wafroc,</span>
<span id="cb52-49"><a href="froc-sample-size.html#cb52-49"></a>         <span class="at">Cov3 =</span> Cov3_wafroc,</span>
<span id="cb52-50"><a href="froc-sample-size.html#cb52-50"></a>         <span class="at">Var =</span> Var_wafroc))</span>
<span id="cb52-51"><a href="froc-sample-size.html#cb52-51"></a>  power_wafroc[i] <span class="ot">&lt;-</span> ret<span class="sc">$</span>powerRRRC</span>
<span id="cb52-52"><a href="froc-sample-size.html#cb52-52"></a>  </span>
<span id="cb52-53"><a href="froc-sample-size.html#cb52-53"></a>  <span class="cf">if</span> (i <span class="sc">==</span> <span class="dv">11</span>)</span>
<span id="cb52-54"><a href="froc-sample-size.html#cb52-54"></a>  <span class="fu">cat</span>(<span class="st">&quot;effectSizeROC[i] = &quot;</span>, effectSizeROC[i],</span>
<span id="cb52-55"><a href="froc-sample-size.html#cb52-55"></a>      <span class="st">&quot;</span><span class="sc">\n</span><span class="st">effectSizewAFROC[i] = &quot;</span>, effectSizewAFROC[i],</span>
<span id="cb52-56"><a href="froc-sample-size.html#cb52-56"></a>      <span class="st">&quot;</span><span class="sc">\n</span><span class="st">power_roc[i] = &quot;</span>, power_roc[i],</span>
<span id="cb52-57"><a href="froc-sample-size.html#cb52-57"></a>      <span class="st">&quot;</span><span class="sc">\n</span><span class="st">power_wafroc[i] = &quot;</span>, power_wafroc[i], <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)  </span>
<span id="cb52-58"><a href="froc-sample-size.html#cb52-58"></a>}</span></code></pre></div>
<pre><code>## effectSizeROC[i] =  0.035 
## effectSizewAFROC[i] =  0.07592683 
## power_roc[i] =  0.2342887 
## power_wafroc[i] =  0.7972542</code></pre>
<p>Lines 2-4 extract the variance components using the ROC-AUC figure of merit. Lines 7-9 extract the variance components using the wAFROC-AUC figure of merit. These are passed to <code>SsPowerGivenJK</code> at lines 27 and 30, respectively. Line 14 defines the number of readers and cases in the pivotal study. The for-loop calculates ROC power (line 28) and wAFROC power (line 31).</p>
<p>Since the wAFROC effect size is 2.169 times the ROC effect size, wAFROC power is larger than that for ROC. For example, for ROC effect size = 0.035 the wAFROC effect size is 0.076, the ROC power is 0.234 while the wAFROC power is 0.797. The influence of the increased wAFROC effect size is magnified as it enters as the square in the formula for statistical power: this overwhelms the increase, noted previously, in variability of wAFROC-AUC relative to ROC-AUC</p>
<p>The following is a plot of the respective powers.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:unnamed-chunk-17"></span>
<img src="19-froc-sample-size_files/figure-html/unnamed-chunk-17-1.png" alt="Plot of wAFROC power vs. ROC power. For ROC effect size = 0.035 the wAFROC effect size is 0.0759, the ROC power is 0.234 while the wAFROC power is 0.797" width="672" />
<p class="caption">
FIGURE 10.2: Plot of wAFROC power vs. ROC power. For ROC effect size = 0.035 the wAFROC effect size is 0.0759, the ROC power is 0.234 while the wAFROC power is 0.797
</p>
</div>
</div>
</div>
<div id="part-2" class="section level2 hasAnchor" number="10.4">
<h2><span class="header-section-number">10.4</span> Part 2<a href="froc-sample-size.html#part-2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="introduction" class="section level3 hasAnchor" number="10.4.1">
<h3><span class="header-section-number">10.4.1</span> Introduction<a href="froc-sample-size.html#introduction" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>This example uses the FED dataset as a pilot FROC study and function <code>SsFrocNhRsmModel()</code> to construct the NH model (encapsulating some of the code in the first part).</p>
</div>
<div id="constructing-the-nh-model-for-the-dataset" class="section level3 hasAnchor" number="10.4.2">
<h3><span class="header-section-number">10.4.2</span> Constructing the NH model for the dataset<a href="froc-sample-size.html#constructing-the-nh-model-for-the-dataset" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>One starts by extracting the first two treatments from <code>dataset04</code>, which represent the NH dataset. Next one constructs the NH model. <code>lesDistr</code> can be specified independent of that in the pilot dataset. This allows some control over selection of the diseased cases in the pivotal study. However, in this example it is simply extracted from the pilot dataset (line 2). Line 3 applies the function <code>SsFrocNhRsmModel</code> to calculate the NH RSM parameters and the scale factor.</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb54-1"><a href="froc-sample-size.html#cb54-1"></a>frocNhData <span class="ot">&lt;-</span> <span class="fu">DfExtractDataset</span>(dataset04, <span class="at">trts =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb54-2"><a href="froc-sample-size.html#cb54-2"></a>lesDistr <span class="ot">&lt;-</span> <span class="fu">UtilLesDistr</span>(frocNhData) <span class="co"># this can be replaced by the anticipated lesion distribution</span></span>
<span id="cb54-3"><a href="froc-sample-size.html#cb54-3"></a>ret <span class="ot">&lt;-</span> <span class="fu">SsFrocNhRsmModel</span>(frocNhData, <span class="at">lesDistr =</span> lesDistr<span class="sc">$</span>Freq)</span>
<span id="cb54-4"><a href="froc-sample-size.html#cb54-4"></a>muNH <span class="ot">&lt;-</span> ret<span class="sc">$</span>mu</span>
<span id="cb54-5"><a href="froc-sample-size.html#cb54-5"></a>lambdaNH <span class="ot">&lt;-</span> ret<span class="sc">$</span>lambda</span>
<span id="cb54-6"><a href="froc-sample-size.html#cb54-6"></a>nuNH <span class="ot">&lt;-</span> ret<span class="sc">$</span>nu</span>
<span id="cb54-7"><a href="froc-sample-size.html#cb54-7"></a>scaleFactor <span class="ot">&lt;-</span> ret<span class="sc">$</span>scaleFactor</span></code></pre></div>
<p>The fitting model is defined by <code>muNH</code> = 3.3121519, <code>lambdaNH</code> = 1.714368 and <code>nuNH</code> = 0.7036564 and <code>lesDistr$Freq</code> = 0.69, 0.2, 0.11. The effect size scale factor is <code>scaleFactor</code> = 2.1693379. All of these are identical to the Part I values.</p>
</div>
<div id="froc-sample-size-variance-components" class="section level3 hasAnchor" number="10.4.3">
<h3><span class="header-section-number">10.4.3</span> Extract the wAFROC variance components<a href="froc-sample-size.html#froc-sample-size-variance-components" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The code applies <code>StSignificanceTesting()</code> to <code>frocNhData</code>, using <code>FOM = "wAFROC"</code> and extracts the variance components.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="froc-sample-size.html#cb55-1" aria-hidden="true" tabindex="-1"></a>varComp_wafroc  <span class="ot">&lt;-</span> <span class="fu">StSignificanceTesting</span>(</span>
<span id="cb55-2"><a href="froc-sample-size.html#cb55-2" aria-hidden="true" tabindex="-1"></a>  frocNhData, </span>
<span id="cb55-3"><a href="froc-sample-size.html#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">FOM =</span> <span class="st">&quot;wAFROC&quot;</span>, </span>
<span id="cb55-4"><a href="froc-sample-size.html#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">&quot;OR&quot;</span>, </span>
<span id="cb55-5"><a href="froc-sample-size.html#cb55-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">analysisOption =</span> <span class="st">&quot;RRRC&quot;</span>)<span class="sc">$</span>ANOVA<span class="sc">$</span>VarCom</span></code></pre></div>
</div>
<div id="wafroc-power-for-specified-roc-effect-size-number-of-readers-and-number-of-cases" class="section level3 hasAnchor" number="10.4.4">
<h3><span class="header-section-number">10.4.4</span> wAFROC power for specified ROC effect size, number of readers and number of cases<a href="froc-sample-size.html#wafroc-power-for-specified-roc-effect-size-number-of-readers-and-number-of-cases" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The following example is for ROC effect size = 0.05, 5 readers (<code>J = 5</code>) and 100 cases (<code>K = 100</code>) in the <strong>pivotal study</strong>.</p>
<pre><code>SsPowerGivenJK(
  dataset,
  ...,
  FOM,
  J,
  K,
  effectSize = NULL,
  alpha = 0.05
)</code></pre>
<p>The function <code>SsPowerGivenJK</code> used below returns the power for specified effect size, numbers of readers and cases, and variance components (supplied as a <code>list</code> via the <code>...</code> argument - see TBA lines xx and yy of following code). The default arguments of this function are:</p>
<pre><code>method = &quot;OR&quot; 
analysisOption = &quot;RRRC&quot; 
LegacyCode = FALSE</code></pre>
<div class="sourceCode" id="cb58"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb58-1"><a href="froc-sample-size.html#cb58-1"></a>effectSizeROC <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb58-2"><a href="froc-sample-size.html#cb58-2"></a>effectSizewAFROC <span class="ot">&lt;-</span> scaleFactor <span class="sc">*</span> effectSizeROC</span>
<span id="cb58-3"><a href="froc-sample-size.html#cb58-3"></a></span>
<span id="cb58-4"><a href="froc-sample-size.html#cb58-4"></a>J <span class="ot">&lt;-</span> <span class="dv">5</span>;K <span class="ot">&lt;-</span> <span class="dv">100</span> <span class="co"># define pivotal study sample size</span></span>
<span id="cb58-5"><a href="froc-sample-size.html#cb58-5"></a></span>
<span id="cb58-6"><a href="froc-sample-size.html#cb58-6"></a>ret <span class="ot">&lt;-</span> <span class="fu">SsPowerGivenJK</span>(</span>
<span id="cb58-7"><a href="froc-sample-size.html#cb58-7"></a>  <span class="at">dataset =</span> <span class="cn">NULL</span>, </span>
<span id="cb58-8"><a href="froc-sample-size.html#cb58-8"></a>  <span class="at">FOM =</span> <span class="st">&quot;wAFROC&quot;</span>, </span>
<span id="cb58-9"><a href="froc-sample-size.html#cb58-9"></a>  <span class="at">J =</span> J, </span>
<span id="cb58-10"><a href="froc-sample-size.html#cb58-10"></a>  <span class="at">K =</span> K, </span>
<span id="cb58-11"><a href="froc-sample-size.html#cb58-11"></a>  <span class="at">effectSize =</span> effectSizewAFROC, </span>
<span id="cb58-12"><a href="froc-sample-size.html#cb58-12"></a>    <span class="fu">list</span>(<span class="at">JStar =</span> JStar, <span class="at">KStar =</span> KStar, </span>
<span id="cb58-13"><a href="froc-sample-size.html#cb58-13"></a>         <span class="at">VarTR =</span> varTR_wafroc,</span>
<span id="cb58-14"><a href="froc-sample-size.html#cb58-14"></a>         <span class="at">Cov1 =</span> Cov1_wafroc,</span>
<span id="cb58-15"><a href="froc-sample-size.html#cb58-15"></a>         <span class="at">Cov2 =</span> Cov2_wafroc,</span>
<span id="cb58-16"><a href="froc-sample-size.html#cb58-16"></a>         <span class="at">Cov3 =</span> Cov3_wafroc,</span>
<span id="cb58-17"><a href="froc-sample-size.html#cb58-17"></a>         <span class="at">Var =</span> Var_wafroc))</span>
<span id="cb58-18"><a href="froc-sample-size.html#cb58-18"></a>power_wafroc <span class="ot">&lt;-</span> ret<span class="sc">$</span>powerRRRC</span>
<span id="cb58-19"><a href="froc-sample-size.html#cb58-19"></a></span>
<span id="cb58-20"><a href="froc-sample-size.html#cb58-20"></a><span class="fu">cat</span>(<span class="st">&quot;ROC-ES = &quot;</span>, effectSizeROC, </span>
<span id="cb58-21"><a href="froc-sample-size.html#cb58-21"></a>    <span class="st">&quot;, wAFROC-ES = &quot;</span>, effectSizeROC <span class="sc">*</span> scaleFactor, </span>
<span id="cb58-22"><a href="froc-sample-size.html#cb58-22"></a>    <span class="st">&quot;, Power-wAFROC = &quot;</span>, power_wafroc, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## ROC-ES =  0.05 , wAFROC-ES =  0.10846689 , Power-wAFROC =  0.97777633</code></pre>
</div>
<div id="number-of-cases-for-80-percent-power-for-a-given-number-of-readers" class="section level3 hasAnchor" number="10.4.5">
<h3><span class="header-section-number">10.4.5</span> Number of cases for 80 percent power for a given number of readers<a href="froc-sample-size.html#number-of-cases-for-80-percent-power-for-a-given-number-of-readers" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<pre><code>SsSampleSizeKGivenJ(
  dataset,
  ...,
  J,
  FOM,
  effectSize = NULL,
  alpha = 0.05,
  desiredPower = 0.8,
)</code></pre>
<p>The function <code>SsSampleSizeKGivenJ</code> returns the number of cases needed for desired power = 0.8 for wAFROC effect size as just listed and wAFROC variance components computed in Section <a href="froc-sample-size.html#froc-sample-size-variance-components">10.4.3</a>.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode numberSource r numberLines"><code class="sourceCode r"><span id="cb61-1"><a href="froc-sample-size.html#cb61-1"></a>ret2 <span class="ot">&lt;-</span> <span class="fu">SsSampleSizeKGivenJ</span>(</span>
<span id="cb61-2"><a href="froc-sample-size.html#cb61-2"></a>  <span class="at">dataset =</span> <span class="cn">NULL</span>, </span>
<span id="cb61-3"><a href="froc-sample-size.html#cb61-3"></a>  <span class="at">J =</span> <span class="dv">6</span>, </span>
<span id="cb61-4"><a href="froc-sample-size.html#cb61-4"></a>  <span class="at">effectSize =</span> effectSizewAFROC, </span>
<span id="cb61-5"><a href="froc-sample-size.html#cb61-5"></a>  <span class="fu">list</span>(<span class="at">JStar =</span> JStar, <span class="at">KStar =</span> KStar, </span>
<span id="cb61-6"><a href="froc-sample-size.html#cb61-6"></a>       <span class="at">VarTR =</span> varTR_wafroc,</span>
<span id="cb61-7"><a href="froc-sample-size.html#cb61-7"></a>       <span class="at">Cov1 =</span> Cov1_wafroc,</span>
<span id="cb61-8"><a href="froc-sample-size.html#cb61-8"></a>       <span class="at">Cov2 =</span> Cov2_wafroc,</span>
<span id="cb61-9"><a href="froc-sample-size.html#cb61-9"></a>       <span class="at">Cov3 =</span> Cov3_wafroc,</span>
<span id="cb61-10"><a href="froc-sample-size.html#cb61-10"></a>       <span class="at">Var =</span> Var_wafroc))</span>
<span id="cb61-11"><a href="froc-sample-size.html#cb61-11"></a></span>
<span id="cb61-12"><a href="froc-sample-size.html#cb61-12"></a><span class="fu">cat</span>(<span class="st">&quot;ROC-ES = &quot;</span>, effectSizeROC, </span>
<span id="cb61-13"><a href="froc-sample-size.html#cb61-13"></a>    <span class="st">&quot;, wAFROC-ES = &quot;</span>, effectSizeROC <span class="sc">*</span> scaleFactor, </span>
<span id="cb61-14"><a href="froc-sample-size.html#cb61-14"></a>    <span class="st">&quot;, K80RRRC = &quot;</span>, ret2<span class="sc">$</span>KRRRC, </span>
<span id="cb61-15"><a href="froc-sample-size.html#cb61-15"></a>    <span class="st">&quot;, Power-wAFROC = &quot;</span>, ret2<span class="sc">$</span>powerRRRC, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>## ROC-ES =  0.05 , wAFROC-ES =  0.10846689 , K80RRRC =  41 , Power-wAFROC =  0.80087319</code></pre>
<p>Here <code>K80RRRC</code> is the number of cases needed for 80 percent power under RRRC analysis.</p>
</div>
</div>
<div id="part-3" class="section level2 hasAnchor" number="10.5">
<h2><span class="header-section-number">10.5</span> Part 3<a href="froc-sample-size.html#part-3" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="application-to-all-available-froc-datasets" class="section level3 hasAnchor" number="10.5.1">
<h3><span class="header-section-number">10.5.1</span> Application to all available FROC datasets<a href="froc-sample-size.html#application-to-all-available-froc-datasets" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>This is an application of the method to all my available FROC datasets.</p>
<div id="tony-dataset" class="section level4 hasAnchor" number="10.5.1.1">
<h4><span class="header-section-number">10.5.1.1</span> TONY dataset<a href="froc-sample-size.html#tony-dataset" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<pre><code>## dataset =  dataset01 , Name =  TONY , I =  2 , J =  5</code></pre>
<pre><code>## $effectSizeROC
## [1] 0.07
## 
## $scaleFactor
## [1] 1.6123687
## 
## $powerRoc
## [1] 0.36353662
## 
## $powerFroc
## [1] 0.7648341</code></pre>
</div>
<div id="fed-dataset-all-data-and-nh-treatments-only" class="section level4 hasAnchor" number="10.5.1.2">
<h4><span class="header-section-number">10.5.1.2</span> FED dataset, all data and NH treatments only<a href="froc-sample-size.html#fed-dataset-all-data-and-nh-treatments-only" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<pre><code>## dataset =  dataset04 , Name =  FEDERICA , I =  5 , J =  4</code></pre>
<pre><code>## All data</code></pre>
<pre><code>## $effectSizeROC
## [1] 0.05
## 
## $scaleFactor
## [1] 1.8536914
## 
## $powerRoc
## [1] 0.49574243
## 
## $powerFroc
## [1] 0.94085909</code></pre>
<pre><code>## NH treatments only</code></pre>
<pre><code>## $effectSizeROC
## [1] 0.05
## 
## $scaleFactor
## [1] 2.1693379
## 
## $powerRoc
## [1] 0.41954431
## 
## $powerFroc
## [1] 0.97777633</code></pre>
</div>
<div id="thompson-dataset" class="section level4 hasAnchor" number="10.5.1.3">
<h4><span class="header-section-number">10.5.1.3</span> THOMPSON dataset<a href="froc-sample-size.html#thompson-dataset" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<pre><code>## dataset =  dataset05 , Name =  THOMPSON , I =  2 , J =  9</code></pre>
<pre><code>## $effectSizeROC
## [1] 0.05
## 
## $scaleFactor
## [1] 1.7822813
## 
## $powerRoc
## [1] 0.36427919
## 
## $powerFroc
## [1] 0.77624968</code></pre>
</div>
<div id="magnus-dataset" class="section level4 hasAnchor" number="10.5.1.4">
<h4><span class="header-section-number">10.5.1.4</span> MAGNUS dataset<a href="froc-sample-size.html#magnus-dataset" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<pre><code>## dataset =  dataset06 , Name =  MAGNUS , I =  2 , J =  4</code></pre>
<pre><code>## $effectSizeROC
## [1] 0.05
## 
## $scaleFactor
## [1] 2.2393454
## 
## $powerRoc
## [1] 0.26755435
## 
## $powerFroc
## [1] 0.86438847</code></pre>
</div>
<div id="lucy-dataset-all-data-and-nh-treatments-only" class="section level4 hasAnchor" number="10.5.1.5">
<h4><span class="header-section-number">10.5.1.5</span> LUCY dataset, all data and NH treatments only<a href="froc-sample-size.html#lucy-dataset-all-data-and-nh-treatments-only" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<pre><code>## dataset =  dataset07 , Name =  LUCY-WARREN , I =  5 , J =  7</code></pre>
<pre><code>## All data</code></pre>
<pre><code>## $effectSizeROC
## [1] 0.06
## 
## $scaleFactor
## [1] 1.6842733
## 
## $powerRoc
## [1] 0.56994854
## 
## $powerFroc
## [1] 0.73874483</code></pre>
<pre><code>## NH treatments only</code></pre>
<pre><code>## $effectSizeROC
## [1] 0.06
## 
## $scaleFactor
## [1] 1.5780687
## 
## $powerRoc
## [1] 0.84058158
## 
## $powerFroc
## [1] 0.98603209</code></pre>
</div>
<div id="dobbins-1-dataset-all-data-and-nh-treatments-only" class="section level4 hasAnchor" number="10.5.1.6">
<h4><span class="header-section-number">10.5.1.6</span> DOBBINS-1 dataset, all data and NH treatments only<a href="froc-sample-size.html#dobbins-1-dataset-all-data-and-nh-treatments-only" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<pre><code>## dataset =  dataset11 , Name =  DOBBINS-1 , I =  4 , J =  5</code></pre>
<pre><code>## All data</code></pre>
<pre><code>## $effectSizeROC
## [1] 0.03
## 
## $scaleFactor
## [1] 1.2364946
## 
## $powerRoc
## [1] 0.15086992
## 
## $powerFroc
## [1] 0.23808322</code></pre>
<pre><code>## NH treatments only</code></pre>
<pre><code>## $effectSizeROC
## [1] 0.03
## 
## $scaleFactor
## [1] 1.4194065
## 
## $powerRoc
## [1] 0.1572418
## 
## $powerFroc
## [1] 0.29602651</code></pre>
</div>
<div id="dobbins-3-dataset-all-data-and-nh-treatments-only" class="section level4 hasAnchor" number="10.5.1.7">
<h4><span class="header-section-number">10.5.1.7</span> DOBBINS-3 dataset, all data and NH treatments only<a href="froc-sample-size.html#dobbins-3-dataset-all-data-and-nh-treatments-only" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<pre><code>## dataset =  dataset13 , Name =  DOBBINS-3 , I =  4 , J =  5</code></pre>
<pre><code>## All data</code></pre>
<pre><code>## $effectSizeROC
## [1] 0.03
## 
## $scaleFactor
## [1] 1.5820231
## 
## $powerRoc
## [1] 0.14448552
## 
## $powerFroc
## [1] 0.25203758</code></pre>
<pre><code>## NH treatments only</code></pre>
<pre><code>## $effectSizeROC
## [1] 0.03
## 
## $scaleFactor
## [1] 1.5437708
## 
## $powerRoc
## [1] 0.41346102
## 
## $powerFroc
## [1] 0.86247586</code></pre>
</div>
</div>
</div>
<div id="discussion" class="section level2 hasAnchor" number="10.6">
<h2><span class="header-section-number">10.6</span> Discussion<a href="froc-sample-size.html#discussion" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>This chapter has described the procedure for FROC sample size estimation.</p>

</div>
</div>



<h3>REFERENCES<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-zanca2009evaluation" class="csl-entry">
Zanca, Federica, Jurgen Jacobs, Chantal Van Ongeval, Filip Claus, Valerie Celis, Catherine Geniets, Veerle Provost, Herman Pauwels, Guy Marchal, and Hilde Bosmans. 2009. <span>“Evaluation of Clinical Image Processing Algorithms Used in Digital Mammography.”</span> <em>Medical Physics</em> 36 (3): 765–75.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="analyzing-froc-data.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="dataset-object-details.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["RJafrocQuickStart.pdf", "RJafrocQuickStart.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
